Nft unstaking duration
DA0-DA0/dao-dao-ui pull request #1694
Opened 2024-02-08 22:33 UTC by ismellike

How does this look? @NoahSaso @CLHRAE
I feel like the NFT selection is starting to get a little cramped. The container should at least show the full NFT card.
Any suggestions? 

![image](https://github.com/DA0-DA0/dao-dao-ui/assets/5104272/fa3afa1c-f7ec-461a-ade7-89dbdaadb6f0)

2024-02-21 02:44 UTC, NoahSaso commented
> How does this look? @NoahSaso @CLHRAE I feel like the NFT selection is starting to get a little cramped. The container should at least show the full NFT card. Any suggestions?
> 
> ![image](https://private-user-images.githubusercontent.com/5104272/303500849-fa3afa1c-f7ec-461a-ade7-89dbdaadb6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODMxNDcsIm5iZiI6MTcwODQ4Mjg0NywicGF0aCI6Ii81MTA0MjcyLzMwMzUwMDg0OS1mYTNhZmExYy1mN2VjLTQ2MWEtYWRlNy04OWRiZGFhZGI2ZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMDIzNDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU5ZTMzMWY2MTM1MDlhNzM3YTQzMTk0YWZlNDhlMzU0ZjZkNjlmNDU2MmFiMTdmOWNiMGQxZTkxYjkyNTZlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jUuvSayT4GLb4IGrELJdlx0QUPaG5CR5b3f7AHIWR-0)


> How does this look? @NoahSaso @CLHRAE I feel like the NFT selection is starting to get a little cramped. The container should at least show the full NFT card. Any suggestions?
> 
> ![image](https://private-user-images.githubusercontent.com/5104272/303500849-fa3afa1c-f7ec-461a-ade7-89dbdaadb6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODM3MDcsIm5iZiI6MTcwODQ4MzQwNywicGF0aCI6Ii81MTA0MjcyLzMwMzUwMDg0OS1mYTNhZmExYy1mN2VjLTQ2MWEtYWRlNy04OWRiZGFhZGI2ZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMDI0MzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzdhNmU2NTY4NDViNjMwYWZhY2YyMDc4ZTliOTAwOTYxYmYwMmJjODNiMzAzYzY0MTAyZDhjYjU2MTMwMWM1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s1DEF8nglZ7w8YDxMtauW0Auhg2ZBlj_fShos3FZg8c)

yeah agreed, this feels too cramped. what if you left everything the same as before, and instead just added the `It will take 2 weeks...` right under the `Stake NFTs`/`Unstake NFTs` buttons?

2024-02-22 00:43 UTC, ismellike commented
> > How does this look? @NoahSaso @CLHRAE I feel like the NFT selection is starting to get a little cramped. The container should at least show the full NFT card. Any suggestions?
> > ![image](https://private-user-images.githubusercontent.com/5104272/303500849-fa3afa1c-f7ec-461a-ade7-89dbdaadb6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODMxNDcsIm5iZiI6MTcwODQ4Mjg0NywicGF0aCI6Ii81MTA0MjcyLzMwMzUwMDg0OS1mYTNhZmExYy1mN2VjLTQ2MWEtYWRlNy04OWRiZGFhZGI2ZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMDIzNDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU5ZTMzMWY2MTM1MDlhNzM3YTQzMTk0YWZlNDhlMzU0ZjZkNjlmNDU2MmFiMTdmOWNiMGQxZTkxYjkyNTZlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jUuvSayT4GLb4IGrELJdlx0QUPaG5CR5b3f7AHIWR-0)
> 
> yeah agreed, this feels too cramped. what if you left everything the same as before, and instead just added the `It will take 2 weeks...` right under the `Stake NFTs`/`Unstake NFTs` buttons? it should probably show up all the time.

I found a typical usage of the `TooltipInfoIcon` in `DaoVotingVaultCard` and applied it at the new location. Here's how it looks now:

![image](https://github.com/DA0-DA0/dao-dao-ui/assets/5104272/0033aee4-5698-44af-886e-542aff930078)

2024-02-22 00:50 UTC, NoahSaso commented
> > > How does this look? @NoahSaso @CLHRAE I feel like the NFT selection is starting to get a little cramped. The container should at least show the full NFT card. Any suggestions?
> > > ![image](https://private-user-images.githubusercontent.com/5104272/303500849-fa3afa1c-f7ec-461a-ade7-89dbdaadb6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODMxNDcsIm5iZiI6MTcwODQ4Mjg0NywicGF0aCI6Ii81MTA0MjcyLzMwMzUwMDg0OS1mYTNhZmExYy1mN2VjLTQ2MWEtYWRlNy04OWRiZGFhZGI2ZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMDIzNDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU5ZTMzMWY2MTM1MDlhNzM3YTQzMTk0YWZlNDhlMzU0ZjZkNjlmNDU2MmFiMTdmOWNiMGQxZTkxYjkyNTZlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jUuvSayT4GLb4IGrELJdlx0QUPaG5CR5b3f7AHIWR-0)
> > 
> > 
> > yeah agreed, this feels too cramped. what if you left everything the same as before, and instead just added the `It will take 2 weeks...` right under the `Stake NFTs`/`Unstake NFTs` buttons? it should probably show up all the time.
> 
> I found a typical usage of the `TooltipInfoIcon` in `DaoVotingVaultCard` and applied it at the new location. Here's how it looks now:
> 
> ![image](https://private-user-images.githubusercontent.com/5104272/306815602-0033aee4-5698-44af-886e-542aff930078.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjMyNzAsIm5iZiI6MTcwODU2Mjk3MCwicGF0aCI6Ii81MTA0MjcyLzMwNjgxNTYwMi0wMDMzYWVlNC01Njk4LTQ0YWYtODg2ZS01NDJhZmY5MzAwNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMDA0OTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmJlOWNhOTQ2MjFhNmQyMWJiNmNhY2IzODEwOGJhYzVkOTI3OWVkMzIwYTRkY2NlMzhhMDMzZjU2YTlkYzAzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1Geu2otKFMl5BA8YbzxNhct18_mrpGXuG83i-PxaWxI)

oh sir that's brilliant! what do you think about moving it above the stake/unstake buttons? so it's under the subtitle.

2024-03-10 08:47 UTC, NoahSaso requested changes
awesome! i think this is the cleanest we'll get for now. thanks :)

just two tiny changes

2024-03-10 08:47 UTC, NoahSaso commented on packages/types/nft.ts
> +import { Duration, GenericToken } from '.'
can you change this import to not import from the index? ie import `GenericToken` from `./token` and `Duration` from its own file too

2024-03-10 08:47 UTC, NoahSaso commented on packages/stateful/components/nft/NftSelectionModal.tsx
> +                <div className="flex flex-row items-center gap-1">
```suggestion
                <div className="-mt-3 flex flex-row items-center gap-1">
```

there's a bit too much spacing now, let's remove some

2024-03-14 23:40 UTC, NoahSaso approved these changes
yay! thank you

2024-03-14 23:41 UTC, merged