Update translation.json
DA0-DA0/dao-dao-ui pull request #860
Opened 2022-09-07 02:34 UTC by DoubleDotC

[comment]: <> (don't forget to run `yarn format` from the root :D)

2022-09-07 02:36 UTC, elsehow approved these changes
Looks great - thanks @DoubleDotC!

2022-09-07 05:08 UTC, NoahSaso approved these changes
thanks!!

2022-10-24 20:01 UTC, NoahSaso requested changes
Looks great! Can you run `yarn format` and push another commit? The JSON formatting is causing lint to fail.

2022-11-02 22:48 UTC, NoahSaso approved these changes

2022-11-02 22:49 UTC, merged